@extends('layouts.master')

@section('title', 'Payment')

@section('content')

@component('partials.breadcrumb',[
'title' => 'Payment List',
'activePage' => 'Payment'
])
@endcomponent

@if(session('success'))
@include('partials.success-alert')
@endif

{{-- Show Warning Alert --}}
@if(session('warning'))
@include('partials.warning-alert')
@endif

<div class="col-lg-12">
    <div class="card mb-4 ">
        <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
            <h6 class="m-0 font-weight-bold text-primary">Payment Table</h6>
        </div>

        <div class="table-responsive p-3">
            <table class="table align-items-center table-flush" id="dataTable">
                <thead class="thead-light">
                    <tr>
                        <th>Name</th>
                        <th>Domain</th>
                        <th>Invoice No</th>
                        <th>Invoice Year</th>
                        <th>Create Date</th>
                        <th>Payment</th>
                        <th>Generated By</th>
                        <th>Actions</th>
                    </tr>
                </thead>
                <tbody>
                    @forelse($invoices as $invoice)
                    <tr>
                        <td>{{ $invoice->findCustomerNameByUserId($invoice->user_id) }}</td>
                        <td>{{ $invoice->service->domain_name }}</td>
                        <td>{{ $invoice->invoice_number }}</td>
                        <td>{{ $invoice->invoice_year }}</td>
                        <td>{{ date('d/m/Y', strtotime($invoice->created_at)) }}</td>
                        <td><button class="btn btn-sm @if($invoice->payment_status == 1) btn-success @elseif($invoice->payment_status == 2) btn-warning @else btn-danger @endif">@if($invoice->payment_status == 1) Paid @elseif($invoice->payment_status == 2) Partial Paid @else Not Paid @endif</button></td>
                        <td>{{ $invoice->user->email }}</td>
                        <td>
                            @if($invoice->payment_status == 0 || $invoice->payment_status == 2)
                            <a href="" class="btn btn-info btn-sm" data-toggle="tooltip" data-placement="top" title="Payment for Invoice No {{ $invoice->invoice_number }}">
                                <i class="fas fa-money-bill"></i>
                            </a>
                            @endif
                            @if(strtotime(date('Y-m-d')) == strtotime(date('Y-m-d', strtotime($invoice->created_at))))
                            <a href="{{ route('invoices.renew',  $invoice->invoice_number) }}" class="btn btn-sm btn-primary" data-toggle="tooltip" data-placement="top" title="Edit Invoice No {{ $invoice->invoice_number }}">
                                <i class="fas fa-edit"></i>
                            </a>
                            @endif
                        </td>
                    </tr>
                    @empty
                    <tr>
                        <td colspan="8" class="text-center">No Invoice Create Yet</td>
                    </tr>
                    @endforelse
                </tbody>
            </table>
        </div>
    </div>
</div>
@endsection